name: Build MadLab Studio (Code-OSS)

on:
  push:
    branches:
      - studio/**
  pull_request:
    branches:
      - studio/**

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, windows-2022, ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: vscode/yarn.lock

      - name: Enable corepack
        run: corepack enable

      - name: Install deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y jq libx11-dev libxkbfile-dev libsecret-1-dev rpm fakeroot

      - name: Install deps (macOS)
        if: runner.os == 'macOS'
        run: brew install jq

      - name: Install deps (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: choco install -y jq

      - name: Yarn install in vscode
        working-directory: vscode
        run: yarn --frozen-lockfile

      - name: Patch product.json
        shell: bash
        run: scripts/patch-product.sh

      - name: Stage branding
        shell: bash
        run: scripts/stage-branding.sh

      - name: Stage built-in extensions
        shell: bash
        run: scripts/stage-extensions.sh

      - name: Build built-in extension
        shell: bash
        run: scripts/build-extensions.sh

      - name: Package (macOS)
        if: runner.os == 'macOS'
        working-directory: vscode
        run: yarn gulp vscode-darwin-arm64-min

      - name: Package (Windows)
        if: runner.os == 'Windows'
        working-directory: vscode
        shell: bash
        run: yarn gulp vscode-win32-x64-min

      - name: Package (Linux)
        if: runner.os == 'Linux'
        working-directory: vscode
        run: yarn gulp vscode-linux-x64-min

      - name: Checksums
        shell: bash
        run: |
          cd vscode/.build
          find . -maxdepth 2 -type f \( -name '*.zip' -o -name '*.tar.gz' -o -name '*.dmg' -o -name '*.exe' \) -exec shasum -a 256 {} \; | tee SHA256SUMS.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: madlab-studio-${{ runner.os }}
          path: vscode/.build


