name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9.15.9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build webview and extension
        run: pnpm -w build

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run unit tests
        run: pnpm test

      - name: Run smoke E2E tests (PR only)
        if: ${{ github.event_name == 'pull_request' }}
        run: pnpm exec playwright test tests/e2e/happy-path.spec.ts tests/e2e/provider-fallback.spec.ts

      - name: Run full E2E tests (push only)
        if: ${{ github.event_name == 'push' }}
        run: pnpm e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.run_id }}
          path: playwright-report/
